### ISSUE TITLE
Can I use the SDK to bridge some tokens not in the list?

### ISSUE THREAD

**Issue by zydjohnHotmail** [mayan-finance/swap-sdk#2]
Hello:
I see there are a number of tokens can be swapped or bridged between different networks.
However, if there are some tokens not in the list, and if I know the contract address of the token, can I use simply use the SDK to swap/bridge them?
Or I can only use the tokens in the list for swapping/bridging?
Please advise, and better with some code samples.
Thanks,

**Comment by mizdler** [comment]
Hey @zydjohnHotmail, Yes! you can use any token you wish! But you might need to run your own relyer to ensure your swap won't get stuck.

If you are not running your own relayer, we suggest picking tokens from our supported list.
What token do you wish to swap? We have a low bar for adding new tokens.

**Comment by zydjohnHotmail** [comment]
Hello:
I didn't read the documents carefully.  What I really want is to bridge, not swap.
One example is: I want to receive some tokens (like USDT) from Solana network, and send the received tokens, less the gas fees, to another address in ERC20 network.
Let me know if it is possible using Mayan SDK.
If yes, show me some code examples.
Thank you very much!

**Comment by mizdler** [comment]
If you wish to receive native USDT (and not the wrapped version) on EVM chains, it's a swap and you can use Mayan SDK.

You can use our UI to try your swap: [swap.mayan.finance](https://swap.mayan.finance)

Using the SDK is pretty straightforward. Follow the doc and let us know if you encounter a problem.

**Comment by zydjohnHotmail** [comment]
Hi, 
Thanks for your quick reply. Tomorrow, I will have some tokens (not USDT, I just use it for example), I want to bridge, not swap.
Then I will try to write some code, but I may need your help.
Thanks,

**Comment by zydjohnHotmail** [comment]
Hi,
Today, I have at least one symbol ‘EFK’, which I want to bridge, send some EFK tokens from ERC20 network to Solana network.
For ‘EFK’, its contract address on Solana network is: efk1hwJ3QNV9dc5qJaLyaw9fhrRdjzDTsxbtWXBh1Xu 
Please advise on how to proceed, if this symbol is not on the support list. What is the steps to bridge it myself, please provide some documents on this topic.
Thanks,

**Comment by mizdler** [comment]
If you only want to bridge a token you can do it using [Portal](https://www.portalbridge.com/) of Wormhole
They also have an SDK that you can use to integrate.

Note that the 'EFK' Token currently has no liquidity on Solana.

**Comment by zydjohnHotmail** [comment]
Hello:
I need detailed instructions. I visit Wormhole Portal, I have install MetaMask wallet, but when I want to connect with my wallet, from the wallet list, MetaMask is missing, there are many other wallets.  Please advise on which wallet I can use, I want to be able to use both in Wormhole Portal and Mayan web page.  
Another information I want to know is: if there is no liquidity on Solana for specific token (EFK), then I can't bridge the token?
I saw one video showing one guy write JavaScript to bridge one token from ERC20 to BEP20, he used something called "Mint/Burn", so the new tokens was generated on the target network, and old ones were burnt.  
For Mayan, I need some liquidity pool on Solana to bridge the tokens?
Please advise,
Thanks,

**Comment by mizdler** [comment]
For using Mayan yes, your token must have liquidity on Solana so relayers can swap it.
For instructions on how to use Wormhole Portal I suggest you drop a message in Wormhole discord where developers of Wormhole can help you.

**Comment by zydjohnHotmail** [comment]
OK, thanks!
