### ISSUE TITLE
Can I use this SDK to bridge some tokens from BEP20 to ERC20 network.

### ISSUE THREAD

**Issue by zydjohnHotmail** [mayan-finance/swap-sdk#3]
Hello:
Now, I have yet another request to do: I want to bridge some DYP (Contract address: 0x961c8c0b1aad0c0b10a51fef6a867e3091bcef17) from BEP20 network to ERC20 network.
Let me know if it is possible with mayan SDK.
Or do I have to use Warmhole?
Please advise,
Thanks,

**Comment by mizdler** [comment]
Hey @zydjohnHotmail 

In this case you need to use Womrhole SDK, Mayan Swap SDK is only meant for swapping tokens and not bridging.

**Comment by zydjohnHotmail** [comment]
Do they have some GUI interface?

**Comment by zydjohnHotmail** [comment]
Hello:
I learned a lesson, to use Wormhole to bridge, I received some wrapped tokens (Wrapped DYP), but when I send the wrapped DYP to a crypto exchange, the exchage refuse to credit it to my account.
Therefore, using Wormhole to bridge DYP in my case, it did NOT work.
I want to know more on Mayan Swap SDK.  How many different tokens it can support? Where I can get the supported tokens list?
Please advise,

**Comment by mizdler** [comment]
Here is API for list of supported tokens by Mayan: https://price-api.mayan.finance/swagger/#/default/TokensController_getTokens

**Comment by zydjohnHotmail** [comment]
Hi,
I looked at the token list, unfortunately, there is no DYP for Ethereum network, it means swap from BEP20 using like USDT to get some DYP on ERC20 is not possible.
Right?

**Comment by zydjohnHotmail** [comment]
Hello:
I want to bridge some BTCBAM tokens from its native network ‘BTCBAM’ to Ethereum (ERC20) network, so I can get some wrapped BTCBAM tokens.
I know its contract address on BSC is: 0x79abC799ae4B749C01e07a60c8687A49D128eA1C
But my MetaMask wallet address is EVM address like: 0x…., I can find one BTCBAM native address is something like this: Bq4Ei1WxgnN6VD5jxeTtMSdvLfK8as7sJM
In order to bridge BTCBAM from its native address to ERC20 address, I think I need some BTCBAM address in my MetaMask wallet, right?  But how can I get one of such address.
I found some articles from BTCBAM web site talking about BTCBAM wallet, I think those address in  BTCBAM wallet should be the native network address.
I want to know if I can use BTCBAM wallet to generate a deposit address, and export the address using the wallet private key, then use MetaMask wallet to import the native BTCBAM address with its wallet private key. If it works, then I can add native BTCBAM wallet address in my MetaMask wallet, then later on go to some bridge web site, to bridge the BTCBAM tokens from its native network to ERC20 network, I want to get the wrapped BTCBAM tokens on ERC20 network.
Please advise if I think in the correct way or not.
Thanks,

**Comment by mizdler** [comment]
Sorry, I can't help you with this. Mayan only supports a subset of networks supported by Wormhole.
